package org.sanbox.tests.tests;// Generated by Selenium IDE
import org.testng.annotations.Test;

public class GroupDeletionTest extends TestBase {

  @Test
  public void groupDeletion() {
    app.getNavigationHelper().goToGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
