package org.sanbox.tests.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.sanbox.tests.model.GroupData;

import java.util.List;

public class GroupDeletionTest extends TestBase {

  @Test
  public void groupDeletion() {
    app.getNavigationHelper().goToGroupPage();
    if (! app.getGroupHelper().isThereAGroup()) {
      app.getGroupHelper().createGroup(new GroupData("test1", null, null));
    }
    List<GroupData> before = app.getGroupHelper().getGroupList(); //начало проверки на количество
    app.getGroupHelper().selectGroup(before.size() - 1); //выбираем конкретную группу указывая в index значение
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
    List<GroupData> after = app.getGroupHelper().getGroupList(); //конец проверки на количество
    Assertions.assertEquals(after.size(), before.size() - 1); //проверка на количество

    before.remove(before.size() - 1);
    for (int i = 0; i < after.size(); i++) {
      Assertions.assertEquals(before.get(i), after.get(i));
    }
  }


}
